# Generated by Django 5.0 on 2024-05-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miradashop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
